server:
  port: 8081

feign:
  client:
    config:
      external-service-city:
        logger-level: full
      default:
        logger-level: basic

logging.level.by.dm13y.example.logging.logging.api: DEBUG