server:
  port: 8081

feign:
  client:
    config:
      default:
        logger-level: full
        requestInterceptors:
          - by.dm13y.example.logging.logging.config.RequestFeignInterceptorConfig

logging.level.by.dm13y.example.logging.logging.api: DEBUG