server:
  port: 8081

feign:
  client:
    config:
      default:
        logger-level: basic
      external-service-city:
        logger-level: full

logging.level.by.dm13y.example.logging.logging.api: DEBUG